// wolox-books/src/app/screens/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { email, password, name } from '../../validators';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { UserService } from '../../services/user.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})

export class RegisterComponent {

  regForm: FormGroup;
  user = {
    locale: "en"
  };

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private userService: UserService,
    private router: Router
  ) {
    this.regForm = fb.group({
      "email": email,
      "password": password,
      "password_confirmation": password,
      "first_name": name,
      "last_name": name,
      "locale": "en"
    });
  };

  createUser = () => {
    console.log(this.user);
    const response = this.userService.registerUser(this.user);    
    response.subscribe(() => console.log('success'));
    this.router.navigate(['login']);
  };

  redirectLogin = () => {
    this.router.navigate(['login']);
  }
}

<form class="form-container" [formGroup]="regForm" (ngSubmit)="createUser()">
  <img class="wolox-logo" src="../../assets/wolox-books.png" alt="Wolox Logo">
  <label class="form-label">First name</label>
    <input class="form-input" type="text" formControlName="first_name" [(ngModel)]="user.first_name">
    <div class="alert" *ngIf="!regForm.controls['first_name'].valid && regForm.controls['first_name'].touched">Este campo es obligatorio</div>
  <label class="form-label">Last name</label>
    <input class="form-input" type="text" formControlName="last_name" [(ngModel)]="user.last_name">
    <div class="alert" *ngIf="!regForm.controls['last_name'].valid && regForm.controls['last_name'].touched">Este campo es obligatorio</div>  
  <label class="form-label">Email</label>
    <input class="form-input" type="text" formControlName="email" [(ngModel)]="user.email">
    <div class="alert" *ngIf="!regForm.controls['email'].valid && regForm.controls['email'].touched">Este campo es obligatorio</div>
  <label class="form-label">Password</label>
    <input class="form-input" type="password" formControlName="password" [(ngModel)]="user.password">
    <div class="alert" *ngIf="!regForm.controls['password'].valid && regForm.controls['password'].touched">Este campo es obligatorio</div>
  <label class="form-label">Password Confirmation</label>
    <input class="form-input" type="password" formControlName="password_confirmation" [(ngModel)]="user.password_confirmation">
    <div class="alert" *ngIf="!regForm.controls['password_confirmation'].valid && regForm.controls['password_confirmation'].touched">Este campo es obligatorio</div>
  <div class="button-container"><button type="submit" class="signup-button" [disabled]="!regForm.valid">Sign up</button></div>
  <button type="button" class="login-button" (click)="redirectLogin()">Login</button>
</form>

// src/views/Register.vue
<template>
  <form class="container" @submit.prevent="onSubmit">
    <img src="../assets/wolox-logo.png" class="wolox-logo" />
    <label class="form-label">First Name</label>
    <input class="input" type="text" v-model="firstName"/>
    <label class="form-label">Last Name</label>
    <input class="input" type="text" v-model="lastName"/>
    <label class="form-label">Email</label>
    <input class="input" type="text" v-model="email"/>
    <p class="error" v-if="!$v.email.email">Email address not valid</p>
    <label class="form-label">Password</label>
    <input class="input" type="password" v-model="password"/>
    <p class="error" v-if="!$v.password.passwordFormat && password">Password should contain at least one number and one upper case</p>
    <button type="submit" class="button signup-button" :disabled="$v.$invalid">Sign Up</button>
    <button class="button login-button" @click="redirectLogin">Login</button>
  </form>
</template>

<script>
import { email } from 'vuelidate/lib/validators'
import { createUser } from '../services/UserService.js'

export default {
  data () {
    return {
      firstName: null,
      lastName: null,
      email: null,
      password: null,
      locale: 'en'
    }
  },
  validations: {
    email: {
      email
    },
    password: {
      passwordFormat(value) {
        const re = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/
        return re.test(value)
      }
    }
  },
  methods: {
    onSubmit() {
      const body = {
        "user": {
          "email": this.email,
          "password": this.password,
          "password_confirmation": this.password,
          "first_name": this.firstName,
          "last_name": this.lastName,
          "locale": "en"
        }
      }
      createUser(body)
    },
    redirectLogin() {
      this.$router.push({ name: 'login' })
    }
  }
}
</script>

<style scoped lang="scss">
@import '../scss/variables/colors';

.container {
  border-top: 3px solid $wolox-blue;
  display: flex;
  flex-direction: column;
  margin: auto;
  margin-top: 80px;
  padding: 20px;
  width: 280px;
}

.wolox-logo {
  align-self: center;
  margin-bottom: 20px;
  width: 250px;
}

.form-label {
  font-size: 12px;
  font-weight: bold;
  margin-top: 10px;
  text-align: left;
}

.signup-button-container {
  border-bottom: 1px solid $grey;
  padding-bottom: 20px;
}

.signup-button {
  background-color: $wolox-green;
  color: $white;
  position: relative;
  width: 100%;

  &:after {
    position: absolute;
    content: " ";
    border: 1px solid $grey;
    width: 100%;
    left: 0;
    top: 50px;
  }

  &:disabled {
    background-color: $grey;
    cursor: not-allowed;
  }
}

.login-button {
  background-color: $transparent;
  border: 2px solid $wolox-green;
  color: $wolox-green;
}

.error {
  color: $red;
  font-size: 11px;
  font-style: italic;
  text-align: left;
}
</style>
